"""signals broadcast_at ustuni

Signal endi IKKI JOYDA yaratilishi mumkin: botda va veb-panelda. Veb
Telegramga xabar yubora olmaydi (kartochka har bir obunachi uchun alohida
yasaladi), shuning uchun u signalni faqat bazaga yozadi; bot esa fon
vazifasida `broadcast_at IS NULL` bo'lganlarni topib tarqatadi.

Revision ID: 26969526e4f4
Revises: da6c8ea490c9
Create Date: 2026-08-27 15:36:35.821235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26969526e4f4'
down_revision: Union[str, None] = 'da6c8ea490c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broadcast_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_signals_broadcast_at'), ['broadcast_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_broadcast_at'))
        batch_op.drop_column('broadcast_at')

    # ### end Alembic commands ###
