"""boshlangich sxema

Revision ID: 9adb13e4b0ec
Revises: 
Create Date: 2026-08-20 02:39:51.865570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9adb13e4b0ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_rulings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('set_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coin_rulings'))
    )
    with op.batch_alter_table('coin_rulings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_rulings_symbol'), ['symbol'], unique=True)

    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_id', sa.String(length=256), nullable=True),
    sa.Column('min_tier', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content'))
    )
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('signals_created', sa.Integer(), nullable=False),
    sa.Column('signals_activated', sa.Integer(), nullable=False),
    sa.Column('tp1_count', sa.Integer(), nullable=False),
    sa.Column('tp2_count', sa.Integer(), nullable=False),
    sa.Column('stop_count', sa.Integer(), nullable=False),
    sa.Column('false_signal_count', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('avg_risk_reward', sa.Float(), nullable=True),
    sa.Column('total_participants', sa.Integer(), nullable=False),
    sa.Column('total_volume_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_stats'))
    )
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_stats_stat_date'), ['stat_date'], unique=True)

    op.create_table('halal_universe_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbols', sa.Text(), nullable=False),
    sa.Column('scanned_depth', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_halal_universe_snapshots'))
    )
    op.create_table('market_health_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=8), nullable=False),
    sa.Column('btc_dominance_score', sa.Float(), nullable=True),
    sa.Column('trend_breadth_score', sa.Float(), nullable=True),
    sa.Column('volatility_score', sa.Float(), nullable=True),
    sa.Column('user_capacity_score', sa.Float(), nullable=True),
    sa.Column('saturation_score', sa.Float(), nullable=True),
    sa.Column('is_daily_preview', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_health_log'))
    )
    with op.batch_alter_table('market_health_log', schema=None) as batch_op:
        batch_op.create_index('ix_market_health_created', ['created_at'], unique=False)

    op.create_table('price_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_details', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_config')),
    sa.UniqueConstraint('tier', 'period', 'currency', name='tier_period_currency')
    )
    op.create_table('risk_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('market_health', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_blocks'))
    )
    with op.batch_alter_table('risk_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_blocks_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_blocks_symbol'), ['symbol'], unique=False)

    op.create_table('risk_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_config'))
    )
    with op.batch_alter_table('risk_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_config_key'), ['key'], unique=True)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=False),
    sa.Column('tp1', sa.Float(), nullable=False),
    sa.Column('tp2', sa.Float(), nullable=False),
    sa.Column('entry_order_type', sa.String(length=8), nullable=False),
    sa.Column('price_at_signal', sa.Float(), nullable=True),
    sa.Column('exit_order_type', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.Text(), nullable=True),
    sa.Column('halal_reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('market_health_at_entry', sa.Float(), nullable=True),
    sa.Column('correlation_group', sa.String(length=32), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('result_pct', sa.Float(), nullable=True),
    sa.Column('is_false_signal', sa.Boolean(), nullable=False),
    sa.Column('postmortem_notes', sa.Text(), nullable=True),
    sa.Column('broadcast_message_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_status'), ['status'], unique=False)
        batch_op.create_index('ix_signals_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('declared_balance_usd', sa.Float(), nullable=True),
    sa.Column('balance_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('signal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_signal_events_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_events'))
    )
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_events_signal_id'), ['signal_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('reminders_sent', sa.String(length=32), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspend_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index('ix_subscriptions_status_expires', ['status', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('user_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('risk_amount_usd', sa.Float(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('partial_exit_price', sa.Float(), nullable=True),
    sa.Column('partial_close_pct', sa.Float(), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_user_positions_signal_id_signals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_positions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_positions')),
    sa.UniqueConstraint('user_id', 'signal_id', name='user_signal')
    )
    with op.batch_alter_table('user_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_positions_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_positions_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index('ix_user_positions_user_date', ['user_id', 'trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_positions_user_id'), ['user_id'], unique=False)

    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.BigInteger(), nullable=True),
    sa.Column('suspended_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_violations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_violations'))
    )
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violations_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('receipt_file_id', sa.String(length=256), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_payments_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))

    op.drop_table('payments')
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violations_user_id'))

    op.drop_table('violations')
    with op.batch_alter_table('user_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_positions_user_id'))
        batch_op.drop_index('ix_user_positions_user_date')
        batch_op.drop_index(batch_op.f('ix_user_positions_trade_date'))
        batch_op.drop_index(batch_op.f('ix_user_positions_signal_id'))

    op.drop_table('user_positions')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index('ix_subscriptions_status_expires')
        batch_op.drop_index(batch_op.f('ix_subscriptions_expires_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_events_signal_id'))

    op.drop_table('signal_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index('ix_signals_status_created')
        batch_op.drop_index(batch_op.f('ix_signals_status'))

    op.drop_table('signals')
    with op.batch_alter_table('risk_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_config_key'))

    op.drop_table('risk_config')
    with op.batch_alter_table('risk_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_blocks_symbol'))
        batch_op.drop_index(batch_op.f('ix_risk_blocks_reason'))

    op.drop_table('risk_blocks')
    op.drop_table('price_config')
    with op.batch_alter_table('market_health_log', schema=None) as batch_op:
        batch_op.drop_index('ix_market_health_created')

    op.drop_table('market_health_log')
    op.drop_table('halal_universe_snapshots')
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_stats_stat_date'))

    op.drop_table('daily_stats')
    op.drop_table('content')
    with op.batch_alter_table('coin_rulings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_rulings_symbol'))

    op.drop_table('coin_rulings')
    # ### end Alembic commands ###
