"""audit_reports jadvali

3.8-band hisoboti faqat Telegramga yuborilardi va shu bilan yo'qolardi.
Endi u saqlanadi: veb-panel ham ko'rsatadi, tarix ham qoladi.

Revision ID: da6c8ea490c9
Revises: a1c4f7d92b03
Create Date: 2026-08-27 02:58:11.730939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6c8ea490c9'
down_revision: Union[str, None] = 'a1c4f7d92b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('rendered', sa.Text(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('traded', sa.Integer(), nullable=False),
    sa.Column('tp2', sa.Integer(), nullable=False),
    sa.Column('tp1_then_stop', sa.Integer(), nullable=False),
    sa.Column('stop', sa.Integer(), nullable=False),
    sa.Column('cancelled', sa.Integer(), nullable=False),
    sa.Column('false_signals', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('average_holding_hours', sa.Float(), nullable=True),
    sa.Column('pattern_count', sa.Integer(), nullable=False),
    sa.Column('sample_warning', sa.Text(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_reports')),
    sa.UniqueConstraint('report_date', 'period_days', name='report_date_period')
    )
    with op.batch_alter_table('audit_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_reports_generated_at'), ['generated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_reports_generated_at'))

    op.drop_table('audit_reports')
    # ### end Alembic commands ###
